DROP DATABASE IF EXISTS SPORTS_MANAGEMENT;
CREATE DATABASE IF NOT EXISTS SPORTS_MANAGEMENT;
DROP USER IF EXISTS 'manager'@'localhost';
GRANT SELECT, INSERT, DELETE, UPDATE
ON SPORTS_MANAGEMENT.*
TO 'manager'@'localhost' IDENTIFIED BY '123456';
USE SPORTS_MANAGEMENT;



CREATE TABLE TEAMS
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TEAM_NAME  VARCHAR(100),
  WIN TINYINT(3) UNSIGNED DEFAULT 0,
  LOSS TINYINT(3) UNSIGNED DEFAULT 0,
  ADMIN_ID INT(10) UNSIGNED NOT NULL,

  CONSTRAINT FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID)

);


CREATE TABLE ADMIN
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100),
  Password VARCHAR(100),
  Name_First VARCHAR(100),
  Name_Last VARCHAR(150) NOT NULL,
 
  
  INDEX (Name_Last),
  INDEX (Name_First, Name_Last)

);


CREATE TABLE GAMES
(

  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Start_day VARCHAR(100),
  End_day VARCHAR(150) NOT NULL,
  Score TINYINT(3) UNSIGNED DEFAULT 0,
  Team_ID INT(10) UNSIGNED NOT NULL,
  ADMIN_ID INT(10) UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID),
  CONSTRAINT FOREIGN KEY (Team_ID) REFERENCES TEAMS(ID)
  
  
);


CREATE TABLE Stats
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Player INT(10) UNSIGNED NOT NULL,
  PlayingTimeMin TINYINT(2) UNSIGNED DEFAULT 0,
  PlayingTimeSec TINYINT(2) UNSIGNED DEFAULT 0,
  Points TINYINT(3) UNSIGNED DEFAULT 0,
  Assists TINYINT(3) UNSIGNED DEFAULT 0,
  Rebounds TINYINT(3) UNSIGNED DEFAULT 0,
  Three_points TINYINT(3) UNSIGNED DEFAULT 0,
  Pts TINYINT(3) UNSIGNED DEFAULT 0,
  Fta TINYINT(3) UNSIGNED DEFAULT 0, 
  Steal TINYINT(3) UNSIGNED DEFAULT 0,
  Turn_over TINYINT(3) UNSIGNED DEFAULT 0,
  Foul TINYINT(3) UNSIGNED DEFAULT 0,
  Block TINYINT(3) UNSIGNED DEFAULT 0,
  Ftm TINYINT(3) UNSIGNED DEFAULT 0,
  ADMIN_ID INT(10) UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID),
  CONSTRAINT FOREIGN KEY (Player) REFERENCES Player(ID),
  CONSTRAINT CHECK (PlayingTimeMin <= 40),
  CONSTRAINT CHECK (PlayingTimeSec <= 60)
);

CREATE TABLE Player
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name_First VARCHAR(100),
  Name_Last VARCHAR(150) NOT NULL,
  Street VARCHAR(250),
  City VARCHAR(100),
  State VARCHAR(100),
  Country VARCHAR(100),
  ZipCode CHAR(10),
  MANAGER_ID INT(10) UNSIGNED NOT NULL,
  TEAM_ID INT(10) UNSIGNED NOT NULL,	
  ADMIN_ID INT(10) UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID),	
  CONSTRAINT FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID),
  CONSTRAINT FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(ID),
  CONSTRAINT CHK_ZipCode CHECK (ZipCode REGEXP '(?!0{5})(?!9{5})\\d{5}(-(?!0{4})(?!9{4})\\d{4})?'),
  INDEX (Name_Last),
  INDEX (Name_First, Name_Last)


);

CREATE TABLE MANAGER
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100),
  Password VARCHAR(100),
  Name_First VARCHAR(100),
  Name_Last VARCHAR(150) NOT NULL,
  Street VARCHAR(250),
  City VARCHAR(100),
  State VARCHAR(100),
  Country VARCHAR(100),
  ZipCode CHAR(10),
  
  CONSTRAINT CHK_ZipCode CHECK (ZipCode REGEXP '(?!0{5})(?!9{5})\\d{5}(-(?!0{4})(?!9{4})\\d{4})?'),
  INDEX (Name_Last),
  INDEX (Name_First, Name_Last)

);

CREATE TABLE TEAM_GAMES
(
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GAME_ID INT(10) UNSIGNED NOT NULL,
  TEAM_ID INT(10) UNSIGNED NOT NULL,

  
  CONSTRAINT FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID),
  CONSTRAINT FOREIGN KEY (GAME_ID ) REFERENCES GAMES(ID)
  	

);
